# https://taskfile.dev

version: '3'


tasks:
  lint:
    desc: Запускаем линтеры
    cmds:
      - golangci-lint run --timeout 15m -v
    silent: true

  build:
    desc: Собираем приложение
    cmds:
      - CGO_ENABLED=0 go build -o bin/service ./cmd/main.go

  mod:
    desc: Обновляем и наводим порядок в go.mod
    cmds:
      - go mod tidy
      - go mod vendor